building:
  image: node:11
  stage: build
  script:
    - npm install --progress=false --no-optional
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - out

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - rm -rf public/*
    - mv out/* public
  artifacts:
    expire_in: 3 days
    paths:
      - public
  only:
    - dev